version: "3.1"
services:
  metabase:
    image: metabase/metabase:v0.46.6.4
    volumes:
      - ./include/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - 3000:3000
    restart: always

version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
    ports:
      - '3001:3000'  # Memetakan port 3000 di container ke port 3000 di host
    volumes:
      - grafana_storage:/var/lib/grafana  # Menyimpan data Grafana secara persisten

volumes:
  grafana_storage: {}  # Mendefinisikan volume grafana_storage untuk data persisten
