# profiles.yml

bank_marketing:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: northern-shield-437204-m0
    dataset: bank_marketing
    threads: 1
    timeout_seconds: 300
    location: US